## @file
# codecov upload configuration file to carryforward coverage results of
# packages that do not upload coverage results for a given pull request.
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
flags:
  CryptoPkg:
    carryforward: true
  MdeModulePkg:
    carryforward: true
  MdePkg:
    carryforward: true
  NetworkPkg:
    carryforward: true
  PcAtChipsetPkg:
    carryforward: true
  PerformancePkg:
    carryforward: true
  PolicyServicePkg:
    carryforward: true
  ShellPkg:
    carryforward: true
  StandaloneMmPkg:
    carryforward: true
  UefiCpuPkg:
    carryforward: true
  UnitTestFrameworkPkg:
    carryforward: true
